### ISSUE TITLE
direct login

### ISSUE THREAD

**Issue by laktak** [dominik-th/matomo-plugin-LoginOIDC#12]
Is it possible to give the users an url that would log them in via oidc without them having to click the login button?

E.g. I tried to open `https://matomo.my.site/index.php?module=LoginOIDC&action=signin` directly but it gives me an error `LoginOIDC_MethodNotAllowed` (because it expects a POST).

**Comment by dominik-th** [comment]
Right now this is not possible, but I agree there are cases where it could be useful.
I will try to include it in the next version

**Comment by dominik-th** [comment]
Added in version 3.0.0
