### ISSUE TITLE
Limit login to configurable list of domains?

### ISSUE THREAD

**Issue by saz** [dominik-th/matomo-plugin-LoginOIDC#14]
Hi!

Thanks for the plugin, it's working for us and almost supports everything we need.

If I'm enabling user creation, is there any way of creating only users who's mail address domain is listed anywhere? I know users won't have any access, but I'd also like to avoid that it's possible to create users at all if it's not from a whitelisted domain?

**Comment by dominik-th** [comment]
Added in version 3.0.0
