### ISSUE TITLE
Matomo wants to verify my password, but I have none

### ISSUE THREAD

**Issue by nogweii** [dominik-th/matomo-plugin-LoginOIDC#20]
Various system administration tasks are set to require the user's password to have been verified recently. (All done via `Piwik\Plugins\Login\PasswordVerifier`)

Would it make sense to forcefully set `$sessionNamespace->lastPasswordAuth` on some ongoing basis? (Every page load, maybe?) Or can the plugin override the verification template and have it check that the user's session is still valid according to the upstream OIDC server?

**Comment by dominik-th** [comment]
In version 4.0.0 you have an extra button to do the authentication reverification via the plugin:
<img width="454" alt="plugin-LoginOIDC_password_confirmation" src="https://user-images.githubusercontent.com/8768490/99903067-4f42fd80-2cc2-11eb-988b-2063eb84af45.png">

**Comment by MagnoBooter** [comment]
There is no such button on password verification required for setting superuser accces:
![Selection_389](https://user-images.githubusercontent.com/3240114/101085096-39311900-35af-11eb-841a-2f96da546395.png)
