### ISSUE TITLE
Log out URL unsupported?

### ISSUE THREAD

**Issue by yrammos** [dominik-th/matomo-plugin-LoginOIDC#23]
@dominik-th, thank you for a very useful plugin.

Unfortunately, I noticed that the the Matomo log out button is not wired to the OIDC session via the IdP logout endpoint (in Keycloak this endpoint looks like `https://my.keycloak.tld/auth/realms/my_realm/protocol/openid-connect/logout`). Might I have misconfigured something? At the moment, even after ostensibly logging out from Matomo, the OIDC login button takes me back into Matomo without a request for credentials!

**Comment by dominik-th** [comment]
Hi @yrammos 
you are right, currently the Matomo logout is not connected in any way to the OIDC provider.

But I agree that it would be nice to support logout urls aswell

**Comment by yrammos** [comment]
Thanks for the quick reply, @dominik-th. I'd tag this as a bug, then, not an enhancement.

**Comment by dominik-th** [comment]
Added in version 3.0.0
