### ISSUE TITLE
New release of the plugin?

### ISSUE THREAD

**Issue by dlecan** [dominik-th/matomo-plugin-LoginOIDC#25]
Hello,

I would like to use the new French translation introduced by the last commit, but it seems to be unreleased.
Is it possible to make a new release?

Thank you

**Comment by dominik-th** [comment]
Hi,

yeah I am going to release a new version in the next few days.
I want to prepare the plugin for Matomo 4.x before doing so

**Comment by pieterhollander** [comment]
I noticed that in the Changelog, version 3.0.0 is mentioned, but this version has not been published on the Matomo marketplace. Would it be possible to do so?

**Comment by dominik-th** [comment]
Sorry, I was busy in the past months.
The new version has been released to the marketplace.

Plugin release for Matomo 4 is still wip
