### ISSUE TITLE
Auth0 Login Hangs

### ISSUE THREAD

**Issue by Kanaderu** [dominik-th/matomo-plugin-LoginOIDC#26]
Hello,

I have the plugin installed and setup to use an existing Auth0 setup. I followed the parameters setup defined here: https://github.com/dominik-th/matomo-plugin-LoginOIDC/blob/master/docs/faq.md

The login page shows up from Auth0 but when signing in, the page hangs (at least for several minutes) on the Auth0 sign-in screen and never completes. The Auth0 logs shows a successful login. When refreshing the page while it is hanging, an error shows up with: `User not found. User could not be created because the OAuth service did not return an email address.` I also have the option `Create new users when users try to log in with unknown ODIC accounts` enabled.

Are there any additions that need to be made to the Auth0 other than setting the `Allowed Callback URLs` parameter?

Settings:
![Screenshot from 2020-08-09 21-22-29](https://user-images.githubusercontent.com/2075208/89746245-afe95a00-da86-11ea-83e8-2276b0a104ca.png)

**Comment by dominik-th** [comment]
Hi there!

When you have automatic user creation enabled you also have to add a scope which provides Matomo the users email address.

Try to set the scope to `openid email`

**Comment by Kanaderu** [comment]
Ah yep, that did the trick!

Thanks!
