### ISSUE TITLE
Trying to access array offset on value of type bool - Matomo 3.14.0

### ISSUE THREAD

**Issue by andrewperry** [dominik-th/matomo-plugin-LoginOIDC#27]
WARNING: /usr/share/matomo/plugins/LoginOIDC/Controller.php(82): Notice - Trying to access array offset on value of type bool - Matomo 3.14.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: UsersManager, Action: userSettings, In CLI mode: false)

This is on PHP 7.4.4 with the ldap config and login also enabled.

**Comment by dominik-th** [comment]
I can't reproduce the issue.
Tried with the same [PHP version](https://hub.docker.com/layers/php/library/php/7.4.4-alpine/images/sha256-f5241aa6459033c513c1ecf3b416a4f1bf945689cb455feca7a322a6963462a9) and [LoginLDAP plugin](https://plugins.matomo.org/LoginLdap) also installed

Please provide detailed steps on how to reproduce

**Comment by dominik-th** [comment]
Closed due to inactivity
