### ISSUE TITLE
Settings cannot be saved with v3.0.0

### ISSUE THREAD

**Issue by ev0lister** [dominik-th/matomo-plugin-LoginOIDC#34]
Settings for initial setup cannot be saved with version 3.0.0. - I do get an HTTP500 with JSON `
"Class 'Piwik\\Plugins\\LoginOIDC\\Exception' not found"` - Works fine with previous version though.

Best regards
Stefan

**Comment by dominik-th** [comment]
Hi Stefan!

I can reproduce the issue when I leave the "Restrict user creation to domains" text field empty.
As a workaround you can whitelist a domain for user creation.

**Comment by ev0lister** [comment]
Okay, what I did is patching as in pull req. #30 described. Afterwards indeed it shows that the "Restrict user creation to domains" text field cannot be empty - it now shows properly the error message. This was not the case before the patch.

**Comment by dominik-th** [comment]
Fixed in 3.0.1
