### ISSUE TITLE
General error 3780 reinstalling plugin after Matomo 4 upgrade.

### ISSUE THREAD

**Issue by tekhnee** [dominik-th/matomo-plugin-LoginOIDC#37]
I used to use the LoginOIDC plugin in the long past (probably under Matomo 2 or the early 3.x versions).

For reasons unrelated to the plugin, I ended up uninstalling it and reverted to Matomo’s built-in login.

Upgrading to Matomo 4.1, I reinstalled this plugin and attempted to enable it. Unfortunately this produced the following error:

`SQLSTATE[HY000]: General error: 3780 Referencing column 'user' and referenced column 'login' in foreign key constraint 'piwik_loginoidc_provider_ibfk_1' are incompatible.`

Neither of the suggestions shown on the screenshot helped. 

Any thoughts? Am reluctant to touch the database without guidance.

Thank you.

![Screen Shot 2020-12-28 at 4 54 10 PM](https://user-images.githubusercontent.com/181365/103224759-01f52400-4931-11eb-8264-c074ffe9a5a1.png)

**Comment by tekhnee** [comment]
UPDATE: This seems to be related to #31. I'm not using LDAP, but I've indeed moved to MySQL 8 since the upgrade to Matomo 4.

**Comment by dominik-th** [comment]
It is the same issue as in #31 so we can close this one
