### ISSUE TITLE
fails to register new user

### ISSUE THREAD

**Issue by blizzz** [dominik-th/matomo-plugin-LoginOIDC#4]
It seems that this is true when a new user logs in: https://github.com/dominik-th/matomo-plugin-LoginOIDC/blob/38eaba03d38f317af57d6682021267aa6fd0df37/Controller.php#L189

Then `linkAccount()` won't be called and thus no provisioning happens. But perhaps I am missing something?

**Comment by blizzz** [comment]
later, in `linkAccount()` the matomo user is being fetched through `Piwik::getCurrentUserLogin()` which yields anonymous. And that does not have view permissions. Is it supposed to work like that?

**Comment by dominik-th** [comment]
The plugin is not meant to register a completely new user.

You can link your account when you are logged in and visit the personal settings page.
Is that what you mean?

**Comment by blizzz** [comment]
@dominik-th I am always ending up with the `LoginOIDC_ExceptionUserNotFound` exception, because the current user is always anonymous.

**Comment by dominik-th** [comment]
For the linking process you have to be logged in.

You can find the button on this settings page:
https://MATOMO_URL/index.php?module=UsersManager&action=userSettings&idSite=1&period=range&date=last30

**Comment by blizzz** [comment]
does it not defeat the purpose of SSO when you need to have a local account first?

**Comment by dominik-th** [comment]
For me it is the convenience as I am logged into my authentication provider anyways and don't have to lookup my matomo password.

But I agree that we could extend the plugin to allow new users to register.
