### ISSUE TITLE
Super User Promotion

### ISSUE THREAD

**Issue by headfox23** [dominik-th/matomo-plugin-LoginOIDC#41]
If I'm a super user which is using oidc as login and want to promote another user to be super user.
Matomo asks me to enter my password.
Entering the oauth password is not working. I assume this part is still trying to check password in db?

**Comment by filhocf** [comment]
This feature is essential! 

Generally when we use oAuth and promote a real user using the account 'admin', we want to do all type of configurations using this new promoted user. Using your plugin is fine the login, but for super users is a bad thing. 

Do you have any prevision about when will work over this question?

**Comment by mstenz** [comment]
Reference an issue here: https://github.com/matomo-org/matomo/issues/19169

**Comment by nebulon42** [comment]
Was apparently fixed in #72.

**Comment by dominik-th** [comment]
Yes, this was fixed in #72 but also requires you to have Matomo 4.12.0 or later which hasn't been released yet
