### ISSUE TITLE
Auto Linking of accounts

### ISSUE THREAD

**Issue by ghost** [dominik-th/matomo-plugin-LoginOIDC#44]
Thank you for the plugin!

Our current scenario is the usage of the plugin in following context:
 - keycloak as OpenID connect provider and SSO Provider
 - manually creating accounts (random passwords) in Matomo by Matomo admins, users should not be created by the LoginOIDC plugin.
 - not every SSO user should have access to Matomo
 - Since keycloak is used as SSO Provider, we don't have user passwords in Matomo. So users can not login to matomo directly and linking of OIDC accounts can not be done by the users themselves.
 - We want to match users by their username (means: matomo user/login ID = keycloak user/login ID)

So our idea was to request a new feature called "auto linking of accounts".

**Comment by chris246** [comment]
Thanks, I was looking for this.
Do you already have a release date planned?
