### ISSUE TITLE
Does LoginOIDC supports Okta?

### ISSUE THREAD

**Issue by MurugeshSellamuthu** [dominik-th/matomo-plugin-LoginOIDC#51]
Hi,

Could you please let me know whether the matamo-Plugin-LoginOIDC supports Okta authendication? Please share any links or documentations if available

Thanks,
Murugesh

**Comment by dominik-th** [comment]
Not tested, but it should be possible.
https://developer.okta.com/docs/reference/api/oidc/#get-started

feel free to update the documentation once you got it running

**Comment by jonathandhn** [comment]
Where should I edit the documentation ? Had just make it happened successfully today on my side.
