### ISSUE TITLE
Latest version not available in Matomo plugins Marketplace

### ISSUE THREAD

**Issue by velcrin** [dominik-th/matomo-plugin-LoginOIDC#62]
Hey, 

it seems that the latest version including https://github.com/dominik-th/matomo-plugin-LoginOIDC/commit/ed137deb617287532e9d5f84b8c20e6f226101cf which is supposed to fix some compatibility issues with 4.x versions of Matomo is not available in https://plugins.matomo.org/LoginOIDC. 

Any chance to get a new release?

Thx!

**Comment by stephane-segning** [comment]
Hi, any updates on this?

**Comment by dominik-th** [comment]
Hello, you can expect a new release in the next few weeks

**Comment by markuslf** [comment]
Hi Dominik,

Do you have any news?

**Comment by dominik-th** [comment]
Hi Markus!

sorry for the delay, there are a couple of small things left I still want to include in the upcoming release. Please stay tuned.

**Comment by dominik-th** [comment]
Version 4.1.0 has been released to the Matomo marketplace
