### ISSUE TITLE
Azure ADB2C

### ISSUE THREAD

**Issue by dotcologne** [dominik-th/matomo-plugin-LoginOIDC#66]
While SSO using Azure AD works perfectly fine, I'm not able to get SSO running with Azure ADB2C. Should ADB2C work as well? Can anyone provide some brief tutorial maybe?

**Comment by Eagle-Admin** [comment]
Could you elaborate how you got Azure AD and SSO to work flawlessly, I'm still running into "Unexpected response from OAuth service." After signing in.

**Comment by dotcologne** [comment]
> Could you elaborate how you got Azure AD and SSO to work flawlessly, I'm still running into "Unexpected response from OAuth service." After signing in.

Puuh, that's too long ago and as it didn't work with Azure ADB2C (but only Azure AD) I finally gave up. 
I only have a screenshot of my Matomo settings left, just in case, not sure if it'll help you.

![grafik](https://user-images.githubusercontent.com/8538077/213435715-0c992a29-68b9-4360-8946-599c914d8a57.png)

**Comment by dotcologne** [comment]
> Could you elaborate how you got Azure AD and SSO to work flawlessly, I'm still running into "Unexpected response from OAuth service." After signing in.

Puuh, that's too long ago and as it didn't work with Azure ADB2C (but only Azure AD) I finally gave up. 
I only have a screenshot of my Matomo settings left, just in case, not sure if it'll help you.

![grafik](https://user-images.githubusercontent.com/8538077/213435192-fd4d7ab7-58f1-4863-94e9-36fd96d25686.png)
