### ISSUE TITLE
"Disable external login for superusers" not working

### ISSUE THREAD

**Issue by OlivierBOEL** [dominik-th/matomo-plugin-LoginOIDC#68]
Hello,

Issue: Superuser can login despite the setting is enabled.
Expected result: OAuth login disabled for superusers.
Analysis: it seems "Piwik::hasTheUserSuperUserAccess($user["login"])" [1] returns **false** because "APIUsersManager::getInstance()->getUsersHavingSuperUserAccess" [2] throws an **exception** (_You must be logged in to access this functionality. /webserver/appl/MATOMO/docs_https_matomo/matomo/core/Access.php:756_).
This is just an assumption. Could be entirely wrong.
Could you please verify?

Many thanks,

Olivier

[1] https://github.com/dominik-th/matomo-plugin-LoginOIDC/blob/4.x-dev/Controller.php#L287

[2] https://github.com/matomo-org/matomo/blob/4.x-dev/core/Piwik.php#L367

**Comment by dominik-th** [comment]
Hi Olivier,

thanks for your analysis!
Should be fixed in 4.1.2

https://github.com/dominik-th/matomo-plugin-LoginOIDC/commit/4c63fd31ad4044d5836eb7e7d71770d8926e03aa
