### ISSUE TITLE
Issues LoginOIDC + ADFS

### ISSUE THREAD

**Issue by miguel-eguizabal** [dominik-th/matomo-plugin-LoginOIDC#7]
Hello,

We are trying to configure Matomo to perform the login using our ADFS, but we are receiving one error from the plugin. Let me share the details:

- Matomo version: 3.11.0
- Authorize URL: https://adfs-instance/adfs/oauth2/authorize
- Token URL: https://adfs-instance/adfs/oauth2/token
- Userinfo URL: https://adfs-instance/adfs/openid/userinfo
- Userinfo ID: sub
- OAuth Scopes: openid
- Redirect URI override: https://matomo-instance/oidc/callback

Since ADFS does not support query parameters for callback URL, we are using this override, and we have a nginx in front of matomo instance to perform the redirection to appropriate matomo URL. 

When we try to login, the request is properly redirected to our ADFS, but when the request comes back to Matomo, unfortunately we are receiving the following error message:

An error occurred
Unknown OAuth provider.

Please, do you have any clue about why we are receiving this error? Maybe we are misconfiguring something. Let me know if further information is needed. 

Thanks a lot in advance!

**Comment by dominik-th** [comment]
Hi there,

I am pretty sure the issue is somewhere in your nginx configuration.

Make sure you set the 'provider' parameter to 'oidc' as mentioned in the [FAQ](https://github.com/dominik-th/matomo-plugin-LoginOIDC/blob/master/docs/faq.md)

**Comment by miguel-eguizabal** [comment]
Hi Dominik,

Sorry for my late response, and thank you so much for your help.

You were completely right, the redirection was not properly configured in nginx, and query parameters was not properly added.

Let me close the issue. Thanks again!
