### ISSUE TITLE
LoginOIDC n'a pas encore été configuré.

### ISSUE THREAD

**Issue by danyocean** [dominik-th/matomo-plugin-LoginOIDC#70]
Hello, 
After installed and configured your plugin for AZURE AD authent, i can see the button on the login page, but then it's appaear: LoginOIDC n'a pas encore été configuré.

I don't understand if i did the settings, i can see them into the matomo_plugin_setting table on mariadb server
![2022-05-18_16-46](https://user-images.githubusercontent.com/397397/169070180-15bc394d-7dc5-4a67-aa96-3ed0a356dc76.png)
.
![2022-05-18_16-47](https://user-images.githubusercontent.com/397397/169070405-4b0d8b66-d5b0-42d9-8c0a-d54a947f999e.png)

Thanks for your help.

**Comment by dominik-th** [comment]
Hello,
you have to set clientId and clientSecret
