### ISSUE TITLE
Support new Password Implementation features

### ISSUE THREAD

**Issue by mstenz** [dominik-th/matomo-plugin-LoginOIDC#72]
There is a new function added
https://github.com/matomo-org/matomo/pull/19525
that fixes a problem with this and other similar plugin
https://github.com/matomo-org/matomo/issues/19169

Please implement this new function in this plugin

**Comment by dominik-th** [comment]
Thanks for letting me know!

Implemented in https://github.com/dominik-th/matomo-plugin-LoginOIDC/commit/a21136a272dee90df944a05ccd2866b65e5b4ed7

Keep in mind the event will be added in Matomo 4.12.0 which has not been released yet. In previous versions the new setting will be ignored.

It will be part of matomo-plugin-LoginOIDC version 4.1.0
