### ISSUE TITLE
Password Confirmation not shown

### ISSUE THREAD

**Issue by OliverW87** [dominik-th/matomo-plugin-LoginOIDC#73]
When using Matomo 4.11.0 with LoginOIDC 4.0.0 the confirmation dialog not shown the OIDC Button.
![101085096-39311900-35af-11eb-841a-2f96da546395](https://user-images.githubusercontent.com/21693797/184235465-4bcf4f3e-0c90-4ce4-87d8-82d8649d298f.png)

**Comment by dominik-th** [comment]
Hi Oliver, this is going to be fixed along with #72
