### ISSUE TITLE
Logout gives a fatal error

### ISSUE THREAD

**Issue by christianhuth** [dominik-th/matomo-plugin-LoginOIDC#74]
Login with LoginOIDC works fine but logout gives this:

![grafik](https://user-images.githubusercontent.com/12433010/187001834-a2f1fbab-006f-4719-b43a-6d1b9130d9e7.png)

I'm using Matomo v.4.11.0 running as Docker container. As OIDC provider I'm using Keycloak v16.1.1 as Docker container.

Similar to issue #69 that should have been fixed by PR #64.

**Comment by dominik-th** [comment]
Hi Christian, this should be fixed in the latest version 4.1.0

**Comment by christianhuth** [comment]
I can confirm, that this works now. Thanks @dominik-th!
